### ISSUE TITLE
[Bug] Having over 276 of some copycat block on a train causes the train to disappear when assembled

### ISSUE THREAD

**Issue by TeslaReloaded** [copycats-plus/copycats#157] opened 2024-09-06 15:25 UTC
**Describe the bug**
When building a train with over 276 blocks from the list below:
- Copycat Half Layer
- Copycat Box
- Copycat Catwalk
- Copycat Byte
- Copycat Board
The train disappears when glued together and assembled.

The example of this bug is on the video:
https://youtu.be/gDvIvLrqOM0

As you can see with 276 blocks the train is assembled correctly, but with 277 blocks it disappears when assembled.

**To Reproduce**
1. Start building a train.
2. Put over 276 blocks from the list above.
3. Glue everything together.
4. Press "Assemble the train" and see it disappear.

**Expected behavior**
Expected the train to not disappear, be visible and interactable.

**Desktop (please complete the following information):**
 - Minecraft 1.20.1
 - Forge 47.3.7
 - Mod Version: copycats-2.1.2+mc.1.20.1-forge.jar

**Additional context**
Full list of mods I use:
amendments-1.20-1.2.11.jar
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
balancedflight-1.20.1_v2.3.0.jar
bellsandwhistles-0.4.3-1.20.x.jar
betterarcheology-1.2.1-1.20.1.jar
bobberdetector-0.1.9-1.20.1.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
botarium-forge-1.20.1-2.3.4.jar
carryon-forge-1.20.1-2.1.2.7.jar
cfwinfo-1.2.0.jar
chunkloaders-1.2.8a-forge-mc1.20.1.jar
cloth-config-11.1.118-forge.jar
collective-1.20.1-7.84.jar
constructionwand-1.20.1-2.11.jar
copycats-2.1.2+mc.1.20.1-forge.jar
cornexpansion-forge-1.0.1.jar
create-1.20.1-0.5.1.h.jar
Create-DnDesire-1.20.1-0.1b.Release-Early-Dev.jar
create-dyn-light-forge1.20.1+1.0.1.jar.disabled
create-netherite-jetpack-1.20.1-1.0.3.jar
create-new-age-forge-1.20.1-1.1.2.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.2.4e.jar
createarmoryv0.6.1n.jar
createcontraptionterminals-1.20-1.0.0.jar
createdeco-2.0.2-1.20.1-forge.jar
createdieselgenerators-1.20.1-1.2i.jar
createloveandwar-0.2-1.20.1.jar
createmetallurgy-0.0.5-1.20.1.jar
createmoredrillheads-2.0.3-1.20.1.jar
createoreexcavation-1.20-1.5.2.jar
createstuffadditionsfix-forge-1.20.1-0.0.0.1.jar
createutilities-0.3.0+1.20.1.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d.jar
create_jetpack-forge-4.2.1.jar
create_mechanical_extruder-1.20.1-1.6.1.h-48.jar
create_misc_and_things_ 1.20.1_4.0A.jar
create_villagerology_1.20.1_0c.jar
cristellib-1.1.5-forge.jar
curios-forge-5.10.0+1.20.1.jar
deco-storage-forge-1.20.1-2.0308.jar
decorative_blocks-forge-1.20.1-4.1.3.jar
design_decor-0.4.0b-1.20.1.jar
doaddonfluids-forge-1.3.0.jar
DramaticDoors-QuiFabrge-1.20.1-3.2.5.jar
dummmmmmy-1.20-1.8.19.jar
durabilitytooltip-1.1.5-forge-mc1.20.jar
dynamiclightsreforged-1.20.1_v1.6.0.jar.disabled
embeddium-0.3.31+mc1.20.1.jar
EnchantmentDescriptions-Forge-1.20.1-17.1.18.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
extendedgears-2.1.1-1.20.1-0.5.1.f-forge.jar
FallingTree-1.20.1-4.3.4.jar
fantasyfurniture-1.20.1-9.0.0.jar
FarmersDelight-1.20.1-1.2.4.jar
flansmod-1.20.1-0.4.193.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
formations-1.0.2a-forge-mc1.20.2.jar
formationsnether-1.0.5.jar
formationsoverworld-1.0.4.jar
FramedBlocks-9.3.1.jar
framework-forge-1.20.1-0.7.8.jar
fusion-1.1.1-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.4.9.jar
guardvillagers-1.20.1-1.6.7.jar
HammerLib-1.20.1-20.1.32.jar
ImprovableSkills-1.20.1-20.1.11.jar
interiors-0.5.4+forge-mc1.20.1.jar
inventorysorter-1.20.1-23.0.1.jar
ironchests-5.0.2-forge.jar
ItemsDisplayedForge-v1.3.0-1.20.1.jar
Jade-1.20.1-forge-11.11.1.jar
jeed-1.20-2.2.2.jar
jei-1.20.1-forge-15.17.0.76.jar
kotlinforforge-4.11.0-all.jar
letsdo-addon-compat-forge-1.4.2.jar
letsdo-API-forge-1.2.15-forge.jar
letsdo-bakery-forge-1.1.15.jar
letsdo-bakery-forge-2.0.2.jar
letsdo-beachparty-forge-1.1.5.jar
letsdo-bloomingnature-forge-1.0.9.jar
letsdo-brewery-forge-1.1.9.jar
letsdo-brewery-forge-2.0.3.jar
letsdo-camping-forge-1.0.3.jar
letsdo-candlelight-forge-1.2.13.jar
letsdo-candlelight-forge-2.0.2.jar
letsdo-farm_and_charm-forge-1.0.3.jar
letsdo-herbalbrews-forge-1.0.8.jar
letsdo-meadow-forge-1.3.19.jar
letsdo-nethervinery-forge-1.2.14.jar
letsdo-vinery-forge-1.4.28.jar
liquidburner-1.20.1-0.5.jar
lmft-1.0.4+1.20.1-forge.jar
mcw-bridges-3.0.0-mc1.20.1forge.jar
mcw-fences-1.1.2-mc1.20.1forge.jar
mcw-furniture-3.3.0-mc1.20.1forge.jar
mcw-holidays-1.1.0-mc1.20.1forge.jar
mcw-lights-1.1.0-mc1.20.1forge.jar
mcw-paths-1.0.5-1.20.1forge.jar
mcw-roofs-2.3.1-mc1.20.1forge.jar
mcw-trapdoors-1.1.3-mc1.20.1forge.jar
mcw-windows-2.3.0-mc1.20.1forge.jar
medieval_seedbags_1.0.1_forge_1.20.1.jar
moonlight-1.20-2.12.17-forge.jar
mysterious_mountain_lib-1.4.7-1.20.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
NekosEnchantedBooks-1.20.1-1.8.0.jar
not_interested--mc1.20.1--forge--1.0.jar
oreharvester-1.20.1-1.4.jar
pattern_schematics-1.1.13+forge-1.20.1.jar
petrolpark-1.20.1-1.0.2.jar
petrolsparts-1.20.1-1.0.3.jar
portablemobs-1.2.0-forge-mc1.20.jar
protection_pixel-1.0.5-forge-1.20.1.jar
PuzzlesLib-v8.1.22-1.20.1-Forge.jar
radiantgear-forge-2.1.5+1.20.1.jar
Realistic-Cobwebs-NeoForge-2.1.0-all.jar
rechiseled-1.1.6-forge-mc1.20.jar
rechiseledcreate-1.0.2-forge-mc1.20.jar
refurbished_furniture-forge-1.20.1-1.0.6.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.29.jar
shutter-2.0.5-1.20.1.jar
sight-1.2.2.jar
slavic-delight-0.1-beta.jar
sliceanddice-forge-3.2.1.jar
sophisticatedbackpacks-1.20.1-3.20.6.1064.jar
sophisticatedcore-1.20.1-0.6.25.632.jar
Stackable Potions-forge-1.20.1-1.0.0.jar
Steam_Rails-1.6.5+forge-mc1.20.1.jar
StorageDrawers-1.20.1-12.6.4.jar
StylishEffects-v8.0.2-1.20.1-Forge.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
supersaturation-1.20.1-5.0.0.jar
tinygates-1.20-4.0.0.jar
tinyredstone-1.20-5.0.2.jar
toms_storage-1.20-1.6.8.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
wardrobe-1.0.3.1-forge-1.20.1.jar
XaerosWorldMap_1.39.0_Forge_1.20.jar
Xaeros_Minimap_24.3.0_Forge_1.20.jar
YungsApi-1.20-Forge-4.0.5.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar

**Comment by hlysine** [comment] 2024-09-06 15:46
I highly suspect that you are hitting the NBT size limit when assembling trains with a lot of copycats. Try increasing that limit in your Create mod config and see if the issue is solved.

**Comment by TeslaReloaded** [comment] 2024-09-06 16:06
Indeed, increasing Max Data Size parameter fixed the issue. Although it's unfortunate that those blocks deplete it so fast.

**Comment by hlysine** [comment] 2024-09-06 16:43
It is pretty unavoidable since those are multistate copycats which need to store multiple materials and consumed items in each block. I'll close this issue since there's not much we can do.

**Closed as not planned by hlysine** 2024-09-06 16:43 UTC
Labels: Bug
