### ISSUE TITLE
[Bug] Light Emmision Not Working After World Reload

### ISSUE THREAD

**Issue by Fischer1000** [copycats-plus/copycats#94] opened 2024-07-15 20:01 UTC
Short description:
Copycat things don't emmit light properly (when applied with light-emmiting blocks) after a world reload.

1. Place any copycat thing and apply a light-emmiting block to it.
2. Exit the world.
3. Log back in.

Expected:
I expected the said blocks to continue emmiting light.

Screenshot:
![Screenshot](https://github.com/user-attachments/assets/3b00cf5e-788a-4e8d-a8c3-a085f2575300)
(After reload of world; The second is a Copycat Block)

Desktop:
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge 47.3.0
 - Mod Version: 1.3.8

**Comment by Bennyboy1695** [comment] 2024-07-15 20:29
This is a create issue and sadly has been for quite a while now.
Also a duplicate of https://github.com/copycats-plus/copycats/issues/52

**Closed as completed by Bennyboy1695** 2024-07-15 20:29 UTC
Labels: Bug, Duplicate
