### ISSUE TITLE
[Bug] Copycat block not emitting light when light emitting block is applied.

### ISSUE THREAD

**Issue by WackyWouter** [copycats-plus/copycats#150] opened 2024-08-20 14:04 UTC
**Describe the bug**
When using a copycat block, like the beam block, and you apply a light emitting block like glowstone, the copycat block does not give off light. The normal copycat blocks that come with the create mod itself do have that functionality.

**To Reproduce**
1. Take a copycat block from the copycats+ mod (like the beam)
2. Apply glowstone to it
3. See it not light up

**Expected behavior**
I expect it to work the same as the normal create block and thus give off light when a light emitting block is applied

**Screenshots**
Video of the behaviour

https://github.com/user-attachments/assets/f311f210-b37a-494a-a8be-509d28ac6dcd

**Desktop (please complete the following information):**
 - Minecraft Version: 1.19.2
 - Mod Loader: Forge
 - Mod Version: 2.1.2

**Comment by hlysine** [comment] 2024-08-20 14:07
Duplicate of #142. We have a fix for that but it's not released yet and not tested on 1.19.2 yet.

**Closed as not planned by hlysine** 2024-08-20 14:07 UTC
Labels: Bug

**Comment by WackyWouter** [comment] 2024-08-20 16:18
Any idea when it might be released? Within the next week, month, year?
