### ISSUE TITLE
[Bug] Schematicannon can't print bytes

### ISSUE THREAD

**Issue by joernott** [copycats-plus/copycats#156] opened 2024-09-02 13:26 UTC
**Describe the bug**
When using bytes and not filling all quadrants of the block (that is why I use bytes instead of copycat blocks), the Schematicannon fails to print the block, stating that the inventory is missing "minecraft:air". If you set the cannon to "skip missing blocks", it just skips over the whole block also not printing the bytes.

**To Reproduce**
1. Place bytes in a block and leave some of it empty.
2. Create a schematic from it
3. Position the schematic, put it into the schematicannon, put enough bytes into an adjacent inventory and gunpowder into it
4. Start printing the template

**Expected behavior**
A block containing bytes and air is printed correctly.

**Screenshots**
![2024-09-02_15 19 00](https://github.com/user-attachments/assets/3f8d5aad-3b3b-4e09-b16b-f360ade59eae)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader Fabric
 - Mod Version 2.1.2

**Additional context**

**Comment by Tera458** [comment] 2024-09-02 21:15
Duplicate of this, marked as closed and fixed indev https://github.com/copycats-plus/copycats/issues/147

**Comment by joernott** [comment] 2024-09-03 08:31
Cool, thanks

**Closed as completed** 2024-09-03 08:42 UTC
Labels: Bug
