### ISSUE TITLE
[Bug] Light source blocks forgetting that they are light source (visual)

### ISSUE THREAD

**Issue by Ferrlius** [copycats-plus/copycats#84] opened 2024-07-07 13:50 UTC
**Describe the bug**
placed light source block into copycat after reloading chunk doesn't remember that it needs to emit light

**To Reproduce**
1. place light source block in copycat block (in my case shroomlight in copycat board)
2. reload chunk (by going far from it, by exiting to main menu, or by pressing f3+t)
3. see that it doesn't visually emit light
4. update block by shift right-clicking with empty hand to remind that it should emit light

**Expected behavior**
it should emit light even after reloading chunk

**Screenshots**
[Video where I'm updating block for some reason](https://i.imgur.com/kotC4WG.mp4)

**Desktop:**
 - 1.20.1
 - Fabric
 - 1.3.8

**Additional context**
it's just visual, in f3 it shows that it emits light. seems to be fully client side, it doesn't updates for other players.
if it caused by other mods, I'll try to find mod causing an issue and update you on it.

**Comment by Bennyboy1695** [comment] 2024-07-07 13:53
This is a create issue and sadly has been for quite a while now.
Also a duplicate of #52

**Closed as completed by Bennyboy1695** 2024-07-07 13:53 UTC
Labels: Bug, Duplicate
