### ISSUE TITLE
[Bug] Copycat Ladder Error: Create: Copycats+

### ISSUE THREAD

**Issue by jackhidalgos** [copycats-plus/copycats#126] opened 2024-07-27 21:54 UTC
Hi, the bug I found is that if you place the mimic scalars quickly or consecutively, the game crashes.

![Captura de pantalla 2024-07-27 165143](https://github.com/user-attachments/assets/15b02748-6c0e-4189-a3ae-6b2754f22446)

Minecraft Version: [1.20.1], Mod Loader[Forge], Mod Version [2.0.5]

**Comment by Bennyboy1695** [comment] 2024-07-27 21:57
Please post the crash report. You will find it in the crash-reports folder inside the .minecraft folder

**Comment by hlysine** [comment] 2024-07-28 01:31
Seems like a duplicate of the ladder crash reported on discord. It's already fixed in our code.

**Closed as completed** 2024-07-28 01:31 UTC
Labels: Bug
