### ISSUE TITLE
[Bug] Inconsistent crash of the game (rendering engine) when in place with ton of copycats blocks

### ISSUE THREAD

**Issue by Starfire1147** [copycats-plus/copycats#116] opened 2024-07-24 05:14 UTC
**Describe the bug**
There is a modpack with a bunch of mods (215 to be exact) and, as expected, it has bugs, but, non of them are critical, except one that  is very anoying. It is very inconsistent, and can happen up to 10 times a day, or not happen at all. It happens when I (or other players) walks into a places where a lot of buildings contains copycats blocks. Firstly, I was swearing at Embeddium\Rubidium, as it was rendering issues, but then I got a crash with no rendering mods (except for FRAPI, maybe, as I play with Sinytra Connector). I don't know which of mods whithin the modpack is causing troubles, and if there are mods which are not supported. Embeddium\Rubidium just multiply the chances of getting the error.

**To Reproduce**
1. Go to a place with a lot of copycats.
2. See crash.

**Expected behavior**
Stable work (copium), maybe rendering issues, not crashing the game.

**Screenshots**
-

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge 47.1.3, Sinytra Connector 
 - Mod Version: from 1.3.2 to 2.0.5

**Additional context**
Modlist: https://pastebin.com/BrusLejS
Crash with Rubidium and Copycats 2.0.5: https://pastebin.com/WBGbv07C https://pastebin.com/QVTXNEkp https://pastebin.com/Z4rqb23w https://pastebin.com/ftpj53Tj
Crash with Rubidium and Copycats 1.3.2:  https://pastebin.com/tEgKhxr2
Crash with Embeddium and Copycats 1.3.2: https://pastebin.com/6GiDyre7 https://pastebin.com/x0RpHEsF
Crash with no Embeddium/Rubidium and Copycats 1.3.2: https://pastebin.com/J9QLwRDU https://pastebin.com/dcL0r8QP

I will bring any additional info needed.

**Comment by hlysine** [comment] 2024-07-24 10:32
These crashes are from multiple sources and are caused by null return values when Copycats+ is trying to read the block state of a position in the world. These crashes only originate from Copycats+ because it is trying to process garbage values, but Copycats+ isn't responsible for generating those garbage values.

If you want to get to the bottom of this, add `-Dmixin.debug.export=true` to your JVM arguments and launch the game with your modpack, then zip the whole `.mixin.out` folder in your instance and post it here.

**Comment by Starfire1147** [comment] 2024-07-29 11:20
[crash-2024-07-29_18.17.33-client.txt](https://github.com/user-attachments/files/16411786/crash-2024-07-29_18.17.33-client.txt)
[mixin.out.zip](https://github.com/user-attachments/files/16411788/mixin.out.zip)
Here

**Comment by Starfire1147** [comment] 2024-07-29 11:30
> [crash-2024-07-29_18.17.33-client.txt](https://github.com/user-attachments/files/16411786/crash-2024-07-29_18.17.33-client.txt) [mixin.out.zip](https://github.com/user-attachments/files/16411788/mixin.out.zip) Here

In all other instances of crashes (when it is not connected with copycats++), it is spitting this MountedStorage class too, seems to be the problem

**Comment by hlysine** [comment] 2024-07-29 11:45
That class is completely unrelated. When the JVM argument is set up correctly, you should have a ton of class files in the `.mixin.out` directory. Please double check that you have added `-Dmixin.debug.export=true` to the JVM args, not program args.

**Comment by Starfire1147** [comment] 2024-07-31 12:26
> That class is completely unrelated. When the JVM argument is set up correctly, you should have a ton of class files in the `.mixin.out` directory. Please double check that you have added `-Dmixin.debug.export=true` to the JVM args, not program args.

[mixin.out.zip](https://github.com/user-attachments/files/16441718/mixin.out.zip)

**Comment by hlysine** [comment] 2024-07-31 12:34
Try removing Canary

**Comment by Starfire1147** [comment] 2024-08-04 05:05
> Try removing Canary
[mixin.out (2).zip](https://github.com/user-attachments/files/16486378/mixin.out.2.zip)
[crash-2024-08-03_23.02.02-client.txt](https://github.com/user-attachments/files/16486383/crash-2024-08-03_23.02.02-client.txt)

Still there, but much, much less often
(I must admit, this already aren't copycats+ problem, but copycats blocks from original create, still, it is present)

**Comment by hlysine** [comment] 2024-08-04 05:27
The new crash is completely different and is a concurrency issue. The exact source of it is very hard to pinpoint, and sometimes it is caused by a combination of mods in which removing any one of them solves the issue. It's outside of what we can help as mod devs, so I'll close this issue now. If this isn't your pack, you may want to find the modpack dev for help.

(PS The crash is caused by a concurrent modification in the render thread, so you are still looking for a rendering-related mod that is causing the issue. I'd suggest removing Starlight. Even if it isn't the culprit, Starlight is obsolete in newer versions of Minecraft due to improvements in the vanilla light engine.)

**Closed as completed by hlysine** 2024-08-04 05:27 UTC
Labels: Bug
