### ISSUE TITLE
[Bug] Connecting and transparent block textures not rendering correctly

### ISSUE THREAD

**Issue by SageofTurtles** [copycats-plus/copycats#92] opened 2024-07-14 01:33 UTC
**Describe the bug**
Textures for certain blocks don't render correctly in copycat blocks.  The ones I've noticed are connected textures from the Chipped mod, which don't connect to one another anymore.  I think it was the update that added multistates when these stopped working, but can't recall for certain.

The other issue is transparent blocks, which are rendering with the sides of a copycat block visible between copycat slabs.  I notice this doesn't seem to occur with only Copycats+ and Create installed, but when I add Sodium, Lithium, and Chipped and their dependencies, I get this issue.  Screenshot attached for reference, but I can provide any additional information if needed.

**To Reproduce**
1.  Install the mods listed below.
2. Open a new world and place down a row of copycat slabs (may occur with other copycats too, but I haven't tested that extensively).
3. Apply a transparent block or Chipped block with a connected texture to the copycat.
4. See screenshot for results.

**Expected behavior**
Would expect textures to connect correctly when applicable, and for copycats with transparent block textures applied to not render in other sides of the block.

**Screenshots**
![2024-07-13_20 18 38](https://github.com/user-attachments/assets/edad6118-d46d-49b1-b730-0f1281149463)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: Fabric 0.15.11

 Mods:
- Athena 3.1.2
- Chipped 3.0.6
- Create Fabric 0.5.1.f-build.1417
- Create: Copycats+ 1.3.8
- Fabric API 0.92.2
- Indium 1.0.34
- Resourceful Lib 2.1.25
- Sodium 0.5.11

**Comment by hlysine** [comment] 2024-07-14 02:05
[UNZIP ME copycats-1.3.8-mc.1.20.1-fabric-build.34.zip](https://github.com/user-attachments/files/16215357/UNZIP.ME.copycats-1.3.8-mc.1.20.1-fabric-build.34.zip)

Please try this version. We have completely reworked our rendering system to hopefully fix bugs like these. It will come as a 2.0 release once ready.

**Make sure to back up your world since this version performs some irreversible migration**

**Comment by SageofTurtles** [comment] 2024-07-14 16:22
Thanks for the quick response!  I tested it out in a new profile after verifying it had the same mods and was experiencing the same rendering issues.  When I switched to the version of Copycats+ attached in your message, I was unable to open the testing world I was using.  Crash report attached for more info.

[crash-2024-07-14_11.18.25-client.txt](https://github.com/user-attachments/files/16228075/crash-2024-07-14_11.18.25-client.txt)

**Comment by hlysine** [comment] 2024-07-15 12:27
[UNZIP ME copycats-1.3.8-mc.1.20.1-fabric-build.44.zip](https://github.com/user-attachments/files/16234547/UNZIP.ME.copycats-1.3.8-mc.1.20.1-fabric-build.44.zip)

The crash was caused by an unrelated incompatibility with Indium. Support for Indium has been added in this build. Please try again.

**Comment by SageofTurtles** [comment] 2024-07-16 00:41
I did some playing around with the textures that were having issues using the version of the mod you sent.  It's much improved from the current release, but there are a few instances where it's still not working *quite* right.  Screenshots:

![2024-07-15_19 39 06](https://github.com/user-attachments/assets/8b7bd5cb-88dc-47cf-90a4-16c12965ab55)
![2024-07-15_19 39 10](https://github.com/user-attachments/assets/b36b874d-70a1-431d-949d-5955335dd50c)
![2024-07-15_19 39 28](https://github.com/user-attachments/assets/1799521a-2c8d-4a2b-b9a6-68eb43c4d746)
![2024-07-15_19 39 48](https://github.com/user-attachments/assets/0fbe5462-21e5-4baa-b009-c2ad94bfdc9c)

**Comment by SageofTurtles** [comment] 2024-07-16 00:43
And I'm not quite sure what's going on with the vertical stairs in that third image.  When I place them back-to-back like that, they seem to think they're connecting on a corner.  I don't think it's related to the current issue,  but figured it was worth mentioning.

**Comment by hlysine** [comment] 2024-07-16 01:19
Image 1 is working as intended because faces are not hidden if the adjacent blocks don't completely cover up the face.

Images 2 and 4 are limitations of slope texture cropping. Not sure if there's a better way to crop it while preserving the nice outline on the triangular face.

Image 3 is just vertical stairs being buggy. 😅 I think I've spent hours on it but the logic is just much more complicated than it looks.

**Comment by hlysine** [comment] 2024-07-26 12:47
I'll close this issue for now since the main issue has been fixed in 2.0. The remaining enhancements take more time and will come slowly.

**Closed as completed by hlysine** 2024-07-26 12:47 UTC
Labels: Bug
