### ISSUE TITLE
Server crash when with CopyCats+ added

### ISSUE THREAD

**Issue by Anorak01** [copycats-plus/copycats#6] opened 2024-02-12 10:38 UTC
First I'll start with what happens when the mod is not added:
Error:
https://pastebin.com/xkFD2z80
Basically the Copies and Cats compat tries to call for method in CopyCats+ and since the mod is not there, it crashes the server.

What happens when the mod is added:
Error:
https://pastebin.com/V1pNZZ3e
I don't really have an explanation for what's happening here.

Any suggestions?

**Comment by hlysine** [comment] 2024-02-12 10:48
The first crash has been fixed in Create: Connected v0.7.1. Please download the hotfix and try again.

Not sure what's happening in the second crash yet

**Comment by Anorak01** [comment] 2024-02-12 10:54
Thanks for the quick reply. I tried updating and the following crash is produced:
https://pastebin.com/MXE9B8Lp

**Comment by Anorak01** [comment] 2024-02-12 11:09
*both with and without CopyCats+

**Comment by hlysine** [comment] 2024-02-12 12:29
It isn't entirely clear what the issue is judging from your crash report, and I cannot reproduce your crash on my end. Please try disabling other mods to see which one is incompatible with Create: Connected.

**Comment by Anorak01** [comment] 2024-02-12 14:05
Just tested only with Create: Connected (and normal Create 0.5.1f) in the pack, nothing else. The same error shows up.
It looks like there's a problem with Create: Connected or something, because while it warned that Create was not present (other testing), the modpack still attempted starting and ran into the same error.
I'll try compiling Connected and get back with more info

**Comment by Anorak01** [comment] 2024-02-12 14:10
Also... probably should have mentioned it at the start... I'm using version 1.19.2, 43.3.5 Forge. Tested 43.3.8 and 43.3.0 and all show the same behavior.

**Comment by Anorak01** [comment] 2024-02-12 15:06
Right, I finally managed to compile the 1.19.2 version with the latest copycats in ./libs/ aaand it finally works... 
There seems to be something wrong with the compiled version of Create: Connected 1.19.2

**Comment by hlysine** [comment] 2024-02-12 15:35
Wow that's just unbelievable. The dev version works, the prod version works, the dry-run publish version works, but the actual publish version fails because it is missing the refmap. I can't even imagine what went wrong.

**Comment by Anorak01** [comment] 2024-02-12 15:38
I can't too, it does indeed sound weird. 
Well, I hope I helped a bit. I'd be glad to see it updated/working on CurseForge when you have the time, so I can update my modpack to work finally.

**Comment by hlysine** [comment] 2024-02-12 15:39
Thank you so much for your testing. I'm trying to reset my local repo because the publish script also seems to be corrupted somehow. Will release a hotfix ASAP.

**Comment by Anorak01** [comment] 2024-02-12 15:42
No problem, I tried checking the differences in jars and found that there are some newline format differences? (tho that might be related to me being on windows, if you're on Linux) nothing else overall... Really weird
Hope you don't run into the issue again, finding it was really annoying:D

**Comment by hlysine** [comment] 2024-02-12 16:28
I've released v0.7.2 which should fix the crash. This is what I get when diffing 0.7.2 with 0.7.1: https://pastebin.com/2r1hiB22

Thanks again for your help. Won't have figured it out without you.

**Closed by hlysine** 2024-02-12 16:28 UTC
