### ISSUE TITLE
Light glitch 

### ISSUE THREAD

**Issue by arhp777** [copycats-plus/copycats#60] opened 2024-06-08 09:02 UTC
I use 1.20.1 mc and copycats 1.2.6
If put glowstone in copycats block and reenter the world the block doesn't glow.

**Comment by Bennyboy1695** [comment] 2024-06-08 11:26
Duplicate of https://github.com/copycats-plus/copycats/issues/52. Also an issue in creates copycat class which we extend

**Closed as completed by Bennyboy1695** 2024-06-08 11:26 UTC

**Comment by arhp777** [comment] 2024-06-08 18:25
There is written, that I have to edit file inside create mod. Do you know how?

**Comment by hlysine** [comment] 2024-06-10 02:24
You should leave this to the Create devs. That comment is just a workaround in the source code and editing source code is quite complex.
